### ISSUE TITLE
Semi colon not allowed with GO SUB

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#17]
I am compacting some code and the fact I can use Semi Colon for a repeat command like NEXT A;B;C is great...
but was surprised to find that GO SUB 10;20;30 wasn't allowed
I can understand GO TO not allowed as that would be silly but why GO SUB? :)

**Comment by ZXDunny** [comment]
This is proving to be a bit of a git, as the cached versions of GOTO and GOSUB don't want to be chained. I'll get it sorted.

**Comment by ZXDunny** [comment]
This was a bugger to find. When you use a ";" the compiler adds a new statement marker (so commands and stuff can find where to come back to) and updates the "statement jump table" at the start of the line which SpecBAS uses to quickly find statements inside a line.

After a line has been compiled, SpecBAS runs the peephole optimiser on it - which in this case changes the GOSUBs to GOSUBC (which uses a cache to store the jump destination rather than doing a search every time) which is considerably smaller than a regular GOSUB. Doing this after the line has been compiled means that the statement list gets mucked around and you get a crash.

Fixed, please test.

**Comment by ASH-II** [comment]
Yep that's now doable :)
