### ISSUE TITLE
This program will hang Specbas (Debug) when run (folder attached)

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#2]
10 WINDOW NEW dot,0,0,512,384: WINDOW HIDE dot
20 SPRITE NEW jet,0,0
30 GRAPHIC NEW jj LOAD "jetpac/j1.bmp"
35 GRAPHIC REMAP jj
40 SPRITE ADDFRAME jet,GFX$ jj
50 SPRITE SHOW jet

[Jetpac.zip](https://github.com/ZXDunny/SpecBAS/files/4022302/Jetpac.zip)

**Comment by ZXDunny** [comment]
Probably a thread race condition, as it doesn't happen on my fast Core i7. I'll see if I can nail it down though. Any other tests I can do will be welcomed.

**Comment by ASH-II** [comment]
so I have found an old version of specbas (attached) that it runs ok on (don't know if that helps)
I am now using this to test 
```
5 CLS 0
10 REM WINDOW NEW dot,0,0,512,384: WINDOW HIDE dot
20 SPRITE NEW jet,0,0
30 GRAPHIC NEW jj LOAD "/jetpac/j1.bmp"
35 GRAPHIC REMAP jj
40 SPRITE ADDFRAME jet,GFX$ jj
45 SPRITE SCALE jet,4
50 SPRITE SHOW jet
```

[SpecBAS.zip](https://github.com/ZXDunny/SpecBAS/files/4023002/SpecBAS.zip)

**Comment by ASH-II** [comment]
had a play and using this program...
```
5 CLS 0
20 SPRITE NEW jet,0,0
30 GRAPHIC NEW jj LOAD "/jetpac/j1.bmp"
35 GRAPHIC REMAP jj
40 SPRITE ADDFRAME jet,GFX$ jj
45 SPRITE SCALE jet,4
50 SPRITE SHOW jet
```
will hang
But removing line 50 (SPRITE SHOW) works.

so it's the SPRITE SHOW jet (my last project didn't use sprites) :)

**Comment by ZXDunny** [comment]
Thanks, that gives me a clue. I don't get the issue (I get a 4x Jetman sprite at the top left) but I do get a very, very long pause when the Ok message shows up, so I think it's the presence of sprites on the screen that is causing your issue. I'll keep at it.

**Comment by ZXDunny** [comment]
Ok, found the issue. The editor runs at 60fps whereas the interpreter switches to speccy-style 50fps when running your program. 

My monitor (and, I assume, yours) runs at 60fps. A rather neat set of circumstances arise when sprites are used. 

1. Sprites cause the entire display to update at the current FPS limit so they're always animating.
2. Calls to swapbuffers in OpenGL will wait for the frame to finish before they return.
3. The editor runs at 60fps.

All three of these cause the application to lock up but only when the editor re-appears (the error message at the end of your program is considered part of the editor). Because it's now running at 60fps, and forcing an update every frame (as opposed to every 16 frames usually, to flash the cursor), the OpenGL call was restricting the main thread's ability to service the message queue. 

The solution was, of course, to update the display in the dedicated refresh thread rather than sending a message to the main thread to do it. Because I've now done that, the display is smooth regardless of the number of sprites. Also, sprites are faster to be created and manages as they no longer have to block the display thread.

Test the new binary on the front page and if all is well I'll close the issue.

**Comment by ASH-II** [comment]
looks like it works but the screen is offset and not refreshing when I run it?
![1](https://user-images.githubusercontent.com/58967719/71907068-2cb7fc80-3163-11ea-8211-d120f6885ac8.jpg)

if I move my mouse over the area it updates under the mouse cursor
![2](https://user-images.githubusercontent.com/58967719/71907114-42c5bd00-3163-11ea-8162-e7bdd6c87753.jpg)

and by moving my mouse I can see it works.

**Comment by ZXDunny** [comment]
Just committed a fix for this. It's temporary, as I'm not entirely happy about it, but it seems to work.

**Comment by ASH-II** [comment]
Nope: won't start up at all

![3](https://user-images.githubusercontent.com/58967719/71922192-677d5d00-3182-11ea-81c0-dc0c89befd5f.jpg)

**Comment by ASH-II** [comment]
tried again and it's now working??? :)

![4](https://user-images.githubusercontent.com/58967719/71922504-f25e5780-3182-11ea-96ca-170f69d986f3.png)

**Comment by ZXDunny** [comment]
> Nope: won't start up at all
> 
> ![3](https://user-images.githubusercontent.com/58967719/71922192-677d5d00-3182-11ea-81c0-dc0c89befd5f.jpg)

Looks like another threading/race condition issue. I'll delay startup until the gl context is done.

**Comment by ZXDunny** [comment]
Ok, it turns out that drawing the mouse pointer before we have any memory for a display is a bad idea, so I've turned the pointer off until the main screen is ready.

Also, resizing the main window (Window 0 in SpecBAS) often caused crashes due to a race condition in the sizing code. I've reworked certain protections between the threads and this _should_ now be fixed. Of course, I've not tested this on a slower PC than my main Core i7 so further testing is needed.

There may be other issues related to this - moving the OpenGL system into a thread of its own brings its own challenges and bugs so I could be chasing these problems for a while yet.

**Comment by ASH-II** [comment]
that works :)

**Comment by ZXDunny** [comment]
My god, this was a journey. 

The move from thread-controlled updating to the refresh timer thread caused UI controls to start flickering, so that has now been fixed. This should be the last issue that arose from this fix.

**Comment by ZXDunny** [comment]
Seems like this has now been fixed - there's one more issue with a possible crash when minimising, but that will be fixed with the next commit.
